### ISSUE TITLE
[FEATURE] Add a simple bug report component

### ISSUE THREAD

**Issue by vjspranav** [StagBIN/frontend#21]
A 'Report a Bug button/link' on the bottom right, on the footer. Which will open up a model asking title and description and then submit bug button.

**Comment by avezqureshi14** [comment]
Hello sir , I am really interested in this issue but when i cloned the project and i tried running on my local machine using `npm start run` i was getting the error `'react-scripts' is not recognized as an internal or external command` , and then i tried installing `react scripts` but inspite of that i was unable to start the project it was displaying the same error can you please help me out with that

**Comment by najeebkp** [comment]
Hi @vjspranav , Please assign me this task. I'll take care.

**Comment by vjspranav** [comment]
> Hello sir , I am really interested in this issue but when i cloned the project and i tried running on my local machine using `npm start run` i was getting the error `'react-scripts' is not recognized as an internal or external command` , and then i tried installing `react scripts` but inspite of that i was unable to start the project it was displaying the same error can you please help me out with that

Clone the project
npm install
npm start

this should get you up and running.

**Comment by vjspranav** [comment]
@najeebkp @avezqureshi14 I'll be assigning this issue to both of you. When either of you completes and raises a pull request, please post a screen shot of how the component looks, in this issue comments. 
Please remember: 
If you are wanting this to count for Hacktoberfest please raise the pull request on or after 1st October. let me know if you need any information.
